# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9o76OstEDTmsTu2-zelFUp1wLi_3wVA
"""

# Save this as app.py
import streamlit as st

st.title("Global Development Clustering App")

cluster_option = st.selectbox("Choose Clustering Model", ["KMeans", "DBSCAN"])

if cluster_option == "KMeans":
    st.write(df[['Country', 'KMeans_Cluster']])
elif cluster_option == "DBSCAN":
    st.write(df[['Country', 'DBSCAN_Cluster']])